### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [Shashank02051997/BusBookingUI-Android#1]
Hi @Shashank02051997 , I'm a graphic designer. I want to contribute by designing a logo / icon for your project for free? What do you think?

**Comment by Shashank02051997** [comment]
Sure u can contribute

**Comment by zularizal** [comment]
Hi @Shashank02051997 , sorry it's too late. This is my design logo for your project. This logo is inspired by a book with a dot and a bus. I make it look simple, clean and modern.
What do you think? If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/54105413-8c3f6180-4405-11e9-92ba-257b53926fd0.png)

**Comment by Shashank02051997** [comment]
Thanks, zularizal for this beautiful logo. I will definitely merge ur contribution in my repository.

**Comment by zularizal** [comment]
Okay wait a minute, I will make a pull request for you.

**Comment by zularizal** [comment]
Hi @Shashank02051997 , I have sent pr to you #2
